[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
remappings = ['forge-std/=lib/forge-std/src/']
solc_version = '0.8.19'
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
scroll_sepolia = "https://sepolia-rpc.scroll.io"

[etherscan]
scroll_sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.scrollscan.com/api" }
